### ISSUE TITLE
Home page on Mobile(iPad)

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#13]
![2017-05-17 22 09 53](https://cloud.githubusercontent.com/assets/27643029/26319860/863cb1e8-3ed5-11e7-91ba-654296f01a8e.png)
 
There is a white gap between the top image and the sign up now banner. 
Also, it displays with white space on the right side instead of filling the screen.

**Comment by NicoleLuxcentric** [comment]
It also happens on a regular browser as I size it up and down. 

https://www.dropbox.com/s/2wnk3ds2t1qvx3q/iPad%20display%20size.mp4?dl=0

I will be using my iPad for my events in 2 weeks. 9/19 & 9/21

**Comment by gtritchie** [comment]
Was being caused on regular browser by the added "hidden" menu "...". This caused the menu to wrap to the next line, making things taller, which caused background image to not be tall enough in a certain range.

The issue on the iPad home page only happens if you are logged in as administrator, which puts an extra toolbar of Wordpress stuff at the top, again causing situation where background image is not tall enough. Doesn't happen to regular users.

We couldn't figure out why it was happening in the original screenshot where no user was logged in, but we confirmed it's not a problem now on either of our iPads.

Area on the right happens if you pinch the page, but if you refresh it goes away.
