### ISSUE TITLE
Member discount image is wonky

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#2]
Goal: When a member has a "On the Path Membership" they receive a discount on VIP services. This is identified with a "member discount" image.

Problem: The image that identifies this partially covers the title of the VIP product.

![image](https://cloud.githubusercontent.com/assets/27643029/25074033/f65c63c8-22a7-11e7-936a-0dc789da206a.png)

Repo:
https://www.luxcentric.com/product/inbox-zero-vip/
Possibly caused by the woocommerce membership or Woocommerce plug in.
1. sign in to an account with an "on the path" membership (test account Marion Kyle - See lastpass)
2. https://www.luxcentric.com/product/inbox-zero-vip/

**Comment by gtritchie** [comment]
Fixed with css changes (https://github.com/luxcentric/luxcentric/commit/89fabf6ceada9193b496dac91e7cd43019515e06).

Should now look like this, please try on live site to confirm. :-)
![2017-06-03_18-46-31](https://cloud.githubusercontent.com/assets/10569626/26758232/1bb5fa52-488d-11e7-83bf-e6d1571462c0.png)
